version: '3.8'

services:
  #client:
  #  image: client
  #  build:
  #      dockerfile: Client/Dockerfile
  Login_api:
    image: login
    build:
     dockerfile: Login/Dockerfile
    ports:
    - 8080:80
    - 8081:443
  session_service_api:
   image: session_service
   build:
     dockerfile: SessionService/Dockerfile